actions:
  - type: "SubscriptionListView"
    action: "SpawnResourceGroupListView"
    takeFocus: true
  - type: "ResourceGroupListView"
    action: "SpawnVirtualMachineListView"
    takeFocus: true
  - type: "ResourceGroupListView"
    action: "SpawnAKSClusterListView"
    takeFocus: true
  - type: "VirtualMachineListView"
    action: "SpawnVirtualMachineDetailView"
    takeFocus: false
  - type: "VirtualMachineListView"
    action: "SpawnVirtualMachineCommandListView"
    takeFocus: true
  - type: "VirtualMachineListView"
    action: "SpawnVirtualMachineSerialConsoleView"
    takeFocus: true
  - type: "AKSClusterListView"
    action: "SpawnAKSClusterDetailView"
    takeFocus: false
  - type: "AppLayout"
    action: "Quit"
    takeFocus: true
key_mappings:
  - action: "SpawnResourceGroupListView"
    key: "Enter"
  - action: "SpawnVirtualMachineListView"
    key: "Enter"
  - action: "SpawnVirtualMachineDetailView"
    key: "Enter"
  - action: SpawnAKSClusterListView
    key: "a"
  - action: "SpawnAKSClusterDetailView"
    key: "Enter"
  - action: "SpawnVirtualMachineCommandListView"
    key: "Ctrl-R"
  - action: "SpawnVirtualMachineSerialConsoleView"
    key: "F5"
  - action: "Quit"
    key: "F12"
