actions:
  - type: "SubscriptionListView"
    condition: "SelectItem"
    action: "SpawnResourceGroupListView"
  - type: "ResourceGroupListView"
    condition: "SelectItem"
    action: "SpawnVirtualMachineListView"
  - type: "VirtualMachineListView"
    condition: "SelectItem"
    action: "SpawnVirtualMachineDetailView"
    takeFocus: false
  - type: "VirtualMachineListview"
    condition: "RunCommand"
    action: "SpawnVMCommandView"
    takeFocus: true
  - type: "VirtualMachineListView"
    condition: "Interact"
    action: "SpawnSerialConsoleView"
    takeFocus: true
  - type: "Global"
    condition: "Quit"
    action: "Quit"
key_mappings:
  - action: "SpawnResourceGroupListView"
    key: "Enter"
  - action: "SpawnVirtualMachineListView"
    key: "Enter"
  - action: "SpawnVirtualMachineDetailView"
    key: "Enter"
  - action: "SpawnVMCommandView"
    key: "Ctrl-R"
  - action: "SpawnSerialConsoleView"
    key: "F5"
  - action: "Quit"
    key: "F12"
