views:
  - view: "SubscriptionListView"
    actions:
      - action: "SpawnResourceGroupListView"
        takeFocus: true
        key: "Enter"
        width: 1
  - view: "ResourceGroupListView"
    actions:
      - action: "SpawnResourceTypeListView"
        takeFocus: true
        key: "Enter"
        width: 1
  - view: "VirtualMachineListView"
    actions:
      - action: "SpawnVirtualMachineDetailView"
        takeFocus: false
        key: "Enter"
        width: 3
      - action: "SpawnVirtualMachineCommandListView"
        takeFocus: true
        key: "Ctrl-R"
        width: 3
      - action: "SpawnVirtualMachineSerialConsoleView"
        takeFocus: true
        key: "F5"
        width: 3
  - view: "AKSClusterListView"
    actions:
      - action: "SpawnAKSClusterDetailView"
        takeFocus: false
        key: "Enter"
        width: 3
  - view: "ResourceListView"
    actions:
      - action: "SpawnResourceDetailView"
        takeFocus: false
        key: "Enter"
        width: 3
  - view: "ResourceTypeListView"
    actions:
      - action: "SpawnResourceListView"
        takeFocus: true
        key: "Enter"
        width: 1
  - view: "AppLayout"
    actions:
      - action: "Quit"
        takeFocus:
        key: "F12"
